### ISSUE TITLE
"org.postgresql.util.PSQLException"

### ISSUE THREAD

**Issue by bitcoinminersuk** [jacekschae/learn-reitit-course-files#10]
I am able to retreive recipies fine in the REPL and in the swagger-ui in the browser, but when I try to create an account in the browser or the repl I get the following 500 error:

{
   "type": "exception"
   "class": "org.postgresql.util.PSQLException" 
}

Looking at this is there anything that is obvious to you, I have been trying to fix this for days :-(
after having pretty print on in the router config I also get the following in the terminal:

{:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account"}

--- :request :reitit.ring.middleware.muuntaja/format ---

  {:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account",
   +:muuntaja/request nil,
   +:muuntaja/response #muuntaja.core.FormatAndCharset
   {:charset "utf-8",
    :format "application/json",
    :raw-format "application/json"}}

--- :request :reitit.ring.middleware.exception/exception ---

  {:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account",
   :muuntaja/request nil,
   :muuntaja/response {:charset "utf-8",
                       :format "application/json",
                       :raw-format "application/json"}}

--- :request :reitit.ring.coercion/coerce-request ---

  {:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account",
   :muuntaja/request nil,
   :muuntaja/response {:charset "utf-8",
                       :format "application/json",
                       :raw-format "application/json"}}

--- :request :reitit.ring.coercion/coerce-response ---

  {:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account",
   :muuntaja/request nil,
   :muuntaja/response {:charset "utf-8",
                       :format "application/json",
                       :raw-format "application/json"}}

--- :request :cheffy.middleware/auth0 ---

  {:body #<org.eclipse.jetty.server.HttpInputOverHTTP@262f1e75 HttpInputOverHTTP@262f1e75[c=0,q=0,[0]=null,s=STREAM]>,
   :character-encoding nil,
   :content-length 0,
   :content-type nil,
   :headers {"accept" "application/json",
             "accept-encoding" "gzip, deflate, br",
             "accept-language" "en-GB,en;q=0.9",
             "connection" "keep-alive",
             "content-length" "0",
             "host" "localhost:3000",
             "origin" "http://localhost:3000",
             "referer" "http://localhost:3000/index.html",
             "sec-fetch-dest" "empty",
             "sec-fetch-mode" "cors",
             "sec-fetch-site" "same-origin",
             "sec-gpc" "1",
             "user-agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36"},
   :path-params {},
   :protocol "HTTP/1.1",
   :query-string nil,
   :remote-addr "0:0:0:0:0:0:0:1",
   :request-method :post,
   :scheme :http,
   :server-name "localhost",
   :server-port 3000,
   :ssl-client-cert nil,
   :uri "/v1/account",
   :muuntaja/request nil,
   :muuntaja/response {:charset "utf-8",
                       :format "application/json",
                       :raw-format "application/json"},
   +:claims {}}

--- :response :reitit.ring.middleware.muuntaja/format ---

  {:body {:class "org.postgresql.util.PSQLException", :type "exception"},
   :status 500}

--- :response :reitit.swagger/swagger ---

  {:body -{:class "org.postgresql.util.PSQLException",
           :type "exception"}
         +#<java.io.ByteArrayInputStream@d6b0f33>,
   :status 500,
   +:headers {"Content-Type" "application/json; charset=utf-8"}}

--- :response---

  {:body #<java.io.ByteArrayInputStream@d6b0f33>,
   :headers {"Content-Type" "application/json; charset=utf-8"},
   :status 500}

**Comment by bitcoinminersuk** [comment]
Also when running the recipe test to get with auth :true, I get the correct response from a get request, but the claims map is empty, when on the course it was showing the api.learnreitit.com/roles etc

**Comment by jacekschae** [comment]
Do you still have this problem? Could I assist in any way?

Sorry for my late reply

**Comment by jacekschae** [comment]
Stale. Feel free to reopen this still occurs.
