### ISSUE TITLE
28 - oauth test config "Username-Password-Authentication" default directory setting no longer there - appears moved

### ISSUE THREAD

**Issue by kentbull** [jacekschae/learn-reitit-course-files#14]
The setting for "Username-Password-Authentication" is no longer configurable from the "Settings" panel. 

It appears to have been moved to the "Connections" sub-tab:
![image](https://github.com/jacekschae/learn-reitit-course-files/assets/65027257/7b78a1ae-4e38-4694-8816-4aaceda885eb)

**Comment by jacekschae** [comment]
Just added to the auth section, thanks!
