### ISSUE TITLE
Add the HStore map to recipe-id fix to the notes on video 32.

### ISSUE THREAD

**Issue by kentbull** [jacekschae/learn-reitit-course-files#15]
Add the fix from video 35 into the video notes on video 32. I wasted between 30 and 60 minutes trying to track this down myself. Let's save the next guy some time and trouble.

```clojure
recipe (recipe-db/find-recipe-by-id db {:uid uid :recipe-id recipe-id})
```

to 

```clojure
recipe (recipe-db/find-recipe-by-id db recipe-id)
```

**Comment by jacekschae** [comment]
Just added -- thanks!
