### ISSUE TITLE
Execution error (NullPointerException) at user/eval4870 (user.clj:19). 

### ISSUE THREAD

**Issue by jennet** [jacekschae/learn-reitit-course-files#2]
When trying to follow the Router lesson, I get an error when trying to test the route:

REPL:
```
(app {:request-method :get
        :uri "/v1/recipe"})
Execution error (NullPointerException) at user/eval4870 (user.clj:19).
null
*e
=>
#error{:cause nil,
       :via [{:type java.lang.NullPointerException, :message nil, :at [user$eval4870 invokeStatic "user.clj" 19]}],
       :trace [[user$eval4870 invokeStatic "user.clj" 19]
               [user$eval4870 invoke "user.clj" 19]
               [clojure.lang.Compiler eval "Compiler.java" 7177]
               [clojure.lang.Compiler eval "Compiler.java" 7132]
               [clojure.core$eval invokeStatic "core.clj" 3214]
               [clojure.core$eval invoke "core.clj" 3210]
               [clojure.main$repl$read_eval_print__9086$fn__9089 invoke "main.clj" 437]
               [clojure.main$repl$read_eval_print__9086 invoke "main.clj" 437]
               [clojure.main$repl$fn__9095 invoke "main.clj" 458]
               [clojure.main$repl invokeStatic "main.clj" 458]
               [clojure.main$repl doInvoke "main.clj" 368]
               [clojure.lang.RestFn invoke "RestFn.java" 1523]
               [nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 79]
               [nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
               [nrepl.middleware.interruptible_eval$interruptible_eval$fn__4256$fn__4260
                invoke
                "interruptible_eval.clj"
                142]
               [clojure.lang.AFn run "AFn.java" 22]
               [nrepl.middleware.session$session_exec$main_loop__4357$fn__4361 invoke "session.clj" 171]
               [nrepl.middleware.session$session_exec$main_loop__4357 invoke "session.clj" 170]
               [clojure.lang.AFn run "AFn.java" 22]
               [java.lang.Thread run "Thread.java" 834]]}
```

I have run through the lessons twice, and then grabbed your code from [the following lesson](https://github.com/jacekschae/learn-reitit-course-files/tree/master/increments/13-swagger) and am getting the same error. Which makes me think it must be something configured differently on my system to yours, but I don't know what that could be.

Any ideas as to how I could track down what's wrong and why it might not be picking up the configured routes?

Thanks

**Comment by jacekschae** [comment]
It looks like something that you are trying to invoke is not available. Did you load the namespace - is the `app` defined?

You can evaluate 
```Clojure
(clojure.repl/dir user)
```
to see what vars are available. 

Let me know if this helps.

**Comment by jacekschae** [comment]
Looks like app will be defined but it will be `nil` therefore the error. After loading the namespace it should be initialized to `:chaffy/app`

**Comment by jennet** [comment]
I'm not having much luck, I'll post my REPL output so you can see the commands / order / output. 

Do you mean to load the _user_ namespace in the REPL?

```
Loading dev/src/user.clj... done
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8656 (user.clj:21).
null
(in-ns 'user)
=> #object[clojure.lang.Namespace 0x160490ae "user"]
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8664 (user.clj:21).
null
(clojure.repl/dir user)
app
db
go
halt
reset
reset-all
=> nil
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8680 (form-init11729445829089037696.clj:1).
null
app 
=> nil
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8686 (form-init11729445829089037696.clj:1).
null
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8690 (form-init11729445829089037696.clj:1).
null
(in-ns 'user)
=> #object[clojure.lang.Namespace 0x160490ae "user"]
app
=> nil
(app {:request-method :get
        :uri "/swagger.json"})
Execution error (NullPointerException) at user/eval8700 (form-init11729445829089037696.clj:1).
null
```

**Comment by jacekschae** [comment]
What happens when you evaluate`(-> state/system :cheffy/app)`

I'm assuming that you require `[integrant.repl.state :as state]`

**Comment by jennet** [comment]
> What happens when you evaluate(-> state/system :cheffy/app)

```
(-> state/system :cheffy/app)
=> nil
```

> I'm assuming that you require [integrant.repl.state :as state]

Yes, the code I'm using right now is the files from https://github.com/jacekschae/learn-reitit-course-files/tree/master/increments/13-swagger

It must be that I'm not running the order of events properly :/

**Comment by jennet** [comment]
Managed to get 
```
(-> state/system :cheffy/app)
=> #object[clojure.lang.AFunction$1 0x43ae4dce "clojure.lang.AFunction$1@43ae4dce"]
app 
=> #object[clojure.lang.AFunction$1 0x43ae4dce "clojure.lang.AFunction$1@43ae4dce"]
(app {:request-method :get
        :uri "/v1/recipe"})
=> nil


```

after re-loading file

**Comment by jacekschae** [comment]
That looks better, what if you try another route?
```clojure
(app {:request-method :get
      :uri "/swagger.json"})
```

or
```clojure
(app {:request-method :get
        :uri "/"})
=> {:status 302, :headers {"Location" "/index.html"}, :body ""}
```

**Comment by jennet** [comment]
```
app
=> #object[clojure.lang.AFunction$1 0x395b18c3 "clojure.lang.AFunction$1@395b18c3"]
(app {:request-method :get
      :uri "/v1/recipe"})
=> nil
(app {:request-method :get
      :uri "/swagger.json"})
=> nil
(app {:request-method :get
      :uri "/"})
=> nil

```

**Comment by jacekschae** [comment]
Could you also paste your `router.clj` and `server.clj`?

**Comment by jennet** [comment]
server.clj:

```
(ns cheffy.server
  (:require [reitit.ring :as ring]
            [ring.adapter.jetty :as jetty]
            [integrant.core :as ig]
            [environ.core :refer [env]]
            [cheffy.router :as router]))

(defn app
  [env]
  (router/routes env))

(defmethod ig/prep-key :server/jetty
  [_ config]
  (merge config {:port (Integer/parseInt (env :port))}))

(defmethod ig/init-key :server/jetty
  [_ {:keys [handler port]}]
  (println (str "\nServer running on port " port))
  (jetty/run-jetty handler {:port port :join? false}))

(defmethod ig/init-key :cheffy/app
  [_ config]
  (println "\nStarted app")
  (app config))

(defmethod ig/init-key :db/postgres
  [_ config]
  (println "\nConfigured db")
  (:jdbc-url config))

(defmethod ig/halt-key! :server/jetty
  [_ jetty]
  (.stop jetty))

(defn -main
  [config-file]
  (let [config (-> config-file slurp ig/read-string)]
    (-> config ig/prep ig/init)))

(comment
  (app {:request-method :get
        :uri "/"})
  (-main))
```

**Comment by jennet** [comment]
router.clj 

```
(ns cheffy.router
  (:require [reitit.ring :as ring]
            [cheffy.recipe.routes :as recipe]))

(defn routes
  [env]
  (ring/ring-handler
    (ring/router
      [["/v1"
        (recipe/routes env)]])))
```

**Comment by jennet** [comment]
config.edn

```
{:server/jetty {:handler #ig/ref :cheffy/app
                :port 3000}
 :cheffy/app   {:jdbc-url #ig/ref :db/postgres}
 :db/postgres  {:jdbc-url "jdbc-url"}}
```

**Comment by jacekschae** [comment]
Sorry for your troubles with following the course. I do mistakes when I go thought and they are usually corrected in the following lessons.

Here is the reason why it doesn't work.

```clojure
(defn routes
  [env]
  (ring/ring-handler
    (ring/router
      [["/v1" ; remove nested vector (fixed in the following lesson by adding swagger)
        (recipe/routes env)]])))
```

corrected

```clojure
(defn routes
  [env]
  (ring/ring-handler
    (ring/router
      ["/v1" ; just one vector
       (recipe/routes env)])))
```

**Comment by jennet** [comment]
Thank you. Could you perhaps add to the description of that video that there is a correction to make? https://www.jacekschae.com/courses/learn-reitit-pro/470079-server/1350500-12-router

(I don't tend to move to the next lesson until I can make sure I have the last one working)

**Comment by jacekschae** [comment]
Just updated. In general there are a lot of these moments during the course. So feel free to peak into next lesson if the things don't work.

**Comment by jennet** [comment]
I was also having a problem in my follow-along code (which didn't have the double nested vector mistake), but this was causing a similar error because in order for it to work it seems to need

`(go)`
then _load file_ and THEN
`(app {:request-method :get 
 :uri "/v1/recipes"})`

(whereas I was loading the file, then running `(go)`, then trying to test)

Trying to debug myself and compare to the files from the start of the next lesson compounded my confusion but glad it's sorted one way or another!

> So feel free to peak into next lesson if the things don't work.

I'll try to do that if it comes up again, though if you do know of any "gotchas" like that, a pointer in the description would be great too (and perhaps make sure that the "starting" code of the next lesson has any fixes applied, that's most likely where I'd go to diff code - rather than watch out for them in videos.)

Thanks for your time in hunting this down with me!

ps - happy for this to be closed

**Comment by jennet** [comment]
> Just updated

If I could make a suggestion (from a learner's point of view), perhaps you could change "If the things are not working for you with this lesson take a look at the next vide when we add swagger." to "At 2m 30s there is a small mistake in the route definition, there should be a single vector and not a nested one. Take a look at the source files or follow along the next lesson where this bug is caught" or words to that effect. 

Just so it's not quite as mysterious! :)

**Comment by jacekschae** [comment]
Thank you so much for this. Just updated. If there will be anything else you know where to ask. Thanks again!
