### ISSUE TITLE
Problems with coercion

### ISSUE THREAD

**Issue by bitcoinminersuk** [jacekschae/learn-reitit-course-files#6]
I am currently on video 31 and when I try to run the test I get the following error message.

clojure.lang.ExceptionInfo: Request coercion failed: #reitit.coercion.CoercionError{:spec #Spec{:form (clojure.spec.alpha/keys :req-un [:spec$14684/description :spec$14684/favourite-count :spec$14684/special-offer :spec$14684/name......

**Comment by jacekschae** [comment]
No where in the course there was a `special-offer`. I guess this is something that you added?

**Comment by bitcoinminersuk** [comment]
yes that's something I've added

**Comment by jacekschae** [comment]
Does it mean we can close this one now?
