### ISSUE TITLE
URL's

### ISSUE THREAD

**Issue by bitcoinminersuk** [jacekschae/learn-reitit-course-files#9]
I am going fixing errors in my code and I am sure I will eventually fix them, I was wondering though, when in development and on server I have the eu.auth domains in the same pattern as yours but with my own domain of course.  I have notice though there are many urls through your project https:///api.learnreitit.com/ can I use any domain or does it have to be one I have registered and set up, or would I just use localhost:3000?

thanks

**Comment by jacekschae** [comment]
I guess it depends, hard to say from the description. Sometimes they are not important and sometimes they are. You need to judge based on occurrence.

**Comment by jacekschae** [comment]
Stale.
